# Load dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.read_csv(r'D:\Road to ML\datasets\Training.csv')

# Encode Categorical column using label encoder

In [3]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
ds_new=ds

In [4]:
ds_new['prognosis']=LE.fit_transform(ds['prognosis'])

# Apply train test split

In [5]:
from sklearn.model_selection import train_test_split

x=ds_new.drop('prognosis',axis=1)
y=ds_new['prognosis']

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=42)

X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

# Train Top Classification models

In [6]:
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier


from sklearn.metrics import accuracy_score,confusion_matrix


models={
    'RFC':RandomForestClassifier(n_estimators=100,random_state=42),
    'GBC':GradientBoostingClassifier(n_estimators=100,random_state=42),
    'svc':SVC(kernel='linear'),
    'NB':MultinomialNB(),
    'KNC':KNeighborsClassifier(n_neighbors=5)
}

for name,model in models.items():
    model.fit(X_train,Y_train)
    y_pred=model.predict(X_test)


    print(f"{name} Consuion_matrix: ")
    print(confusion_matrix(Y_test,y_pred))
    print(f"{name} Accuracy is: ")
    print(accuracy_score(Y_test,y_pred))


RFC Consuion_matrix: 
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
RFC Accuracy is: 
1.0
GBC Consuion_matrix: 
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
GBC Accuracy is: 
1.0
svc Consuion_matrix: 
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
svc Accuracy is: 
1.0
NB Consuion_matrix: 
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
NB Accuracy is: 
1.0
KNC Consuion_matrix: 
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
KNC Accuracy is: 
1.0


# Select best model and make some prediction for testing

In [7]:
svc=SVC()
svc.fit(X_train,Y_train)
y_pred=svc.predict(X_test)
print("Accuracy is: ")
print(accuracy_score(Y_test,y_pred))





Accuracy is: 
1.0


In [8]:
print("Test 1")
print("Predicted label: ",svc.predict(X_test.iloc[60].values.reshape(1,-1)))
print("Actual label: ",Y_test.iloc[60])
print("Test 2")
print("Predicted label: ",svc.predict(X_test.iloc[17].values.reshape(1,-1)))
print("Actual label: ",Y_test.iloc[17]) 
print("Test 3")
print("Predicted label: ",svc.predict(X_test.iloc[55].values.reshape(1,-1)))
print("Actual label: ",Y_test.iloc[55])


Test 1
Predicted label:  [25]
Actual label:  25
Test 2
Predicted label:  [22]
Actual label:  22
Test 3
Predicted label:  [20]
Actual label:  20


D:\ML\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
D:\ML\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
D:\ML\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


# Load datasets and use logic for recommendations for given prognosis

In [9]:
symtoms_df=pd.read_csv(r'D:\Road to ML\datasets\symtoms_df.csv')
Symptom_severity=pd.read_csv(r'D:\Road to ML\datasets\Symptom-severity.csv')
precautions_df=pd.read_csv(r'D:\Road to ML\datasets\precautions_df.csv')
diets=pd.read_csv(r'D:\Road to ML\datasets\diets.csv')
description=pd.read_csv(r'D:\Road to ML\datasets\description.csv')
workout_df=pd.read_csv(r'D:\Road to ML\datasets\workout_df.csv')

### Remove unnecessary column from dataset

In [10]:
Symptom_severity

Symptom  weight
0                 itching       1
1               skin_rash       3
2    nodal_skin_eruptions       4
3     continuous_sneezing       4
4               shivering       5
..                    ...     ...
128    inflammatory_nails       2
129               blister       4
130  red_sore_around_nose       2
131     yellow_crust_ooze       3
132             prognosis       5

[133 rows x 2 columns]

In [11]:
diets

Disease  \
0                         Fungal infection   
1                                  Allergy   
2                                     GERD   
3                      Chronic cholestasis   
4                            Drug Reaction   
5                     Peptic ulcer disease   
6                                     AIDS   
7                                 Diabetes   
8                          Gastroenteritis   
9                         Bronchial Asthma   
10                            Hypertension   
11                                Migraine   
12                    Cervical spondylosis   
13            Paralysis (brain hemorrhage)   
14                                Jaundice   
15                                 Malaria   
16                             Chicken pox   
17                                  Dengue   
18                                 Typhoid   
19                             hepatitis A   
20                             Hepatitis B   
21                             Hepatitis C   
22                             Hepatitis D   
23                             Hepatitis E   
24                     Alcoholic hepatitis   
25                            Tuberculosis   
26                             Common Cold   
27                               Pneumonia   
28            Dimorphic hemmorhoids(piles)   
29                            Heart attack   
30                          Varicose veins   
31                          Hypothyroidism   
32                         Hyperthyroidism   
33                            Hypoglycemia   
34                         Osteoarthristis   
35                               Arthritis   
36  (vertigo) Paroymsal Positional Vertigo   
37                                    Acne   
38                 Urinary tract infection   
39                               Psoriasis   
40                                Impetigo   

                                                 Diet  
0   ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...  
1   ['Elimination Diet', 'Omega-3-rich foods', 'Vi...  
2   ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...  
3   ['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot...  
4   ['Antihistamine Diet', 'Omega-3-rich foods', '...  
5   ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...  
6   ['Balanced Diet', 'Protein-rich foods', 'Fruit...  
7   ['Low-Glycemic Diet', 'Fiber-rich foods', 'Lea...  
8   ['Bland Diet', 'Bananas', 'Rice', 'Applesauce'...  
9   ['Anti-Inflammatory Diet', 'Omega-3-rich foods...  
10  ['DASH Diet', 'Low-sodium foods', 'Fruits and ...  
11  ['Migraine Diet', 'Low-Tyramine Diet', 'Caffei...  
12  ['Arthritis Diet', 'Anti-Inflammatory Diet', '...  
13  ['Heart-Healthy Diet', 'Low-sodium foods', 'Fr...  
14  ['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits...  
15  ['Malaria Diet', 'Hydration', 'High-Calorie Di...  
16  ['Chicken Pox Diet', 'High-Calorie Diet', 'Sof...  
17  ['Dengue Diet', 'Hydration', 'High-Calorie Die...  
18  ['Typhoid Diet', 'High-Calorie Diet', 'Soft an...  
19  ['Hepatitis A Diet', 'High-Calorie Diet', 'Sof...  
20  ['Hepatitis B Diet', 'High-Calorie Diet', 'Sof...  
21  ['Hepatitis C Diet', 'High-Calorie Diet', 'Sof...  
22  ['Hepatitis D Diet', 'High-Calorie Diet', 'Sof...  
23  ['Hepatitis E Diet', 'High-Calorie Diet', 'Sof...  
24  ['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits...  
25  ['TB Diet', 'High-Calorie Diet', 'Soft and bla...  
26  ['Cold Diet', 'Hydration', 'Warm fluids', 'Res...  
27  ['Pneumonia Diet', 'High-Calorie Diet', 'Soft ...  
28  ['Hemorrhoids Diet', 'High-Fiber Diet', 'Hydra...  
29  ['Heart-Healthy Diet', 'Low-sodium foods', 'Fr...  
30  ['Varicose Veins Diet', 'High-Fiber Diet', 'Fr...  
31  ['Hypothyroidism Diet', 'Iodine-rich foods', '...  
32  ['Hyperthyroidism Diet', 'Low-Iodine Diet', 'C...  
33  ['Hypoglycemia Diet', 'Complex carbohydrates',...  
34  ['Arthritis Diet', 'Anti-Inflammatory Diet', '...  
35  ['Arthritis Diet', 'Anti-Inflammatory Diet', '...  
36  ['Vertigo Diet', 'Low-Salt

In [12]:
symtoms_df.drop('Unnamed: 0',axis=1,inplace=True)
symtoms_df

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  
0                 skin_rash   nodal_skin_eruptions        dischromic _patches  
1      nodal_skin_eruptions    dischromic _patches                        NaN  
2      nodal_skin_eruptions    dischromic _patches                        NaN  
3                 skin_rash    dischromic _patches                        NaN  
4                 skin_rash   nodal_skin_eruptions                        NaN  
...                     ...                    ...                        ...  
4915               headache                 nausea         spinning_movements  
4916     pus_filled_pimples             blackheads                   scurring  
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine  
4918             joint_pain           skin_peeling        silver_like_dusting  
4919             high_fever                blister       red_sore_around_nose  

[4920 rows x 5 columns]

In [13]:
workout_df.drop('Unnamed: 0',axis=1,inplace=True)
workout_df.drop('Unnamed: 0.1',axis=1,inplace=True)
workout_df

disease                            workout
0    Fungal infection                 Avoid sugary foods
1    Fungal infection                 Consume probiotics
2    Fungal infection          Increase intake of garlic
3    Fungal infection             Include yogurt in diet
4    Fungal infection              Limit processed foods
..                ...                                ...
405          Impetigo  Consult a healthcare professional
406          Impetigo     Follow medical recommendations
407          Impetigo                   Avoid scratching
408          Impetigo        Take prescribed antibiotics
409          Impetigo                Practice wound care

[410 rows x 2 columns]

In [14]:
precautions_df.drop('Unnamed: 0',axis=1,inplace=True)
precautions_df['Precaution_4']= precautions_df['Precaution_4'].fillna('follow up')
precautions_df

Disease  \
0                             Drug Reaction   
1                                   Malaria   
2                                   Allergy   
3                            Hypothyroidism   
4                                 Psoriasis   
5                                      GERD   
6                       Chronic cholestasis   
7                               hepatitis A   
8                           Osteoarthristis   
9   (vertigo) Paroymsal  Positional Vertigo   
10                             Hypoglycemia   
11                                     Acne   
12                                Diabetes    
13                                 Impetigo   
14                            Hypertension    
15                      Peptic ulcer diseae   
16             Dimorphic hemmorhoids(piles)   
17                              Common Cold   
18                              Chicken pox   
19                     Cervical spondylosis   
20                          Hyperthyroidism   
21                  Urinary tract infection   
22                           Varicose veins   
23                                     AIDS   
24             Paralysis (brain hemorrhage)   
25                                  Typhoid   
26                              Hepatitis B   
27                         Fungal infection   
28                              Hepatitis C   
29                                 Migraine   
30                         Bronchial Asthma   
31                      Alcoholic hepatitis   
32                                 Jaundice   
33                              Hepatitis E   
34                                   Dengue   
35                              Hepatitis D   
36                             Heart attack   
37                                Pneumonia   
38                                Arthritis   
39                          Gastroenteritis   
40                             Tuberculosis   

                            Precaution_1                        Precaution_2  \
0                        stop irritation            consult nearest hospital   
1               Consult nearest hospital                     avoid oily food   
2                         apply calamine             cover area with bandage   
3                          reduce stress                            exercise   
4       wash hands with warm soapy water        stop bleeding using pressure   
5                 avoid fatty spicy food       avoid lying down after eating   
6                             cold baths                  anti itch medicine   
7               Consult nearest hospital                  wash hands through   
8                          acetaminophen            consult nearest hospital   
9                               lie down         avoid sudden change in body   
10                      lie down on side                      check in pulse   
11                            bath twice              avoid fatty spicy food   
12                    have balanced diet                            exercise   
13      soak affected area in warm water                     use antibiotics   
14                            meditation                          salt baths   
15                avoid fatty spicy food              consume probiotic food   
16                avoid fatty spicy food                 consume witch hazel   
17           drink vitamin c rich drinks                         take vapour   
18                  use neem in bathing                  consume neem leaves   
19          use heating pad or cold pack                            exercise   
20                           eat healthy                             massage   
21                 drink plenty of water           increase vitamin c intake   
22  lie down flat and raise the leg high                        use oinments   
23                       avoid open cuts                wear ppe if possible   
24                               massage                     

### Make a funtion

In [15]:
symptoms = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of_urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic_patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}


def prediction(symptoms,user_symptoms,diets,workout_df,precautions_df):
    have_symptoms = [0]*132
    for s in user_symptoms:
        if s in symptoms:
            index=symptoms[s]
            have_symptoms[index]=1
    have_symptoms=np.array(have_symptoms).reshape(1,-1)
    predicted=svc.predict(have_symptoms)
    bemari=LE.inverse_transform(predicted)
    diets_=diets.loc[diets['Disease']==bemari[0],'Diet'].values
    workout_df_=workout_df.loc[workout_df['disease']==bemari[0],'workout'].values
    precautions_df_=precautions_df.loc[precautions_df['Disease']==bemari[0],['Precaution_1','Precaution_2','Precaution_3','Precaution_4']].values
    diet_list = eval(diets_[0]) if diets_ else []
    workout_list=workout_df_
    precautions_list=precautions_df_[0]
    print(diet_list)
    print(workout_list)
    print(precautions_list)
    
    
    
user_symptoms =['chest_pain','stomach_bleeding','painful_walking','swollen_blood_vessels']
prediction(symptoms,user_symptoms,diets,workout_df,precautions_df)

['Heart-Healthy Diet', 'Low-sodium foods', 'Fruits and vegetables', 'Whole grains', 'Lean proteins']
['Follow a heart-healthy diet' 'Limit sodium intake'
 'Include fiber-rich foods' 'Consume healthy fats' 'Include lean proteins'
 'Limit sugary foods and beverages' 'Stay hydrated'
 'Consult a healthcare professional' 'Follow medical recommendations'
 'Engage in regular exercise']
['call ambulance' 'chew or swallow asprin' 'keep calm' 'follow up']


D:\ML\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


# Save model and necessary files

In [17]:
import pickle
pickle.dump(svc,open('SVCmodel.pkl', 'wb'))
pickle.dump(LE,open('LE.pkl', 'wb'))
diets.to_csv('Diets_ds.csv',index=False)
workout_df.to_csv('workout_ds.csv',index=False)
precautions_df.to_csv('precautions_ds.csv',index=False)
